from rest_framework.test import APITestCase
from rest_framework import status

class AutoGeneratedPostmanTests(APITestCase):
    base_url = "http://localhost:8000"

    def test_auth_get(self):
        url = self.base_url + "/"
        headers = {'Authorization': 'Bearer YOUR_TOKEN_HERE'}
        response = self.client.get(url, headers=headers)
        self.assertIn(response.status_code, [200, 201, 204], msg=f'Failed {url}: {response.status_code}')

    def test_service_profile_get(self):
        url = self.base_url + "/"
        headers = {'Authorization': 'Bearer YOUR_TOKEN_HERE'}
        response = self.client.get(url, headers=headers)
        self.assertIn(response.status_code, [200, 201, 204], msg=f'Failed {url}: {response.status_code}')

    def test_leadership_profile_get(self):
        url = self.base_url + "/"
        headers = {'Authorization': 'Bearer YOUR_TOKEN_HERE'}
        response = self.client.get(url, headers=headers)
        self.assertIn(response.status_code, [200, 201, 204], msg=f'Failed {url}: {response.status_code}')

    def test_personal_profile_get(self):
        url = self.base_url + "/"
        headers = {'Authorization': 'Bearer YOUR_TOKEN_HERE'}
        response = self.client.get(url, headers=headers)
        self.assertIn(response.status_code, [200, 201, 204], msg=f'Failed {url}: {response.status_code}')

    def test_guidance_get(self):
        url = self.base_url + "/"
        headers = {'Authorization': 'Bearer YOUR_TOKEN_HERE'}
        response = self.client.get(url, headers=headers)
        self.assertIn(response.status_code, [200, 201, 204], msg=f'Failed {url}: {response.status_code}')

    def test_events_get(self):
        url = self.base_url + "/"
        headers = {'Authorization': 'Bearer YOUR_TOKEN_HERE'}
        response = self.client.get(url, headers=headers)
        self.assertIn(response.status_code, [200, 201, 204], msg=f'Failed {url}: {response.status_code}')
