# Generated by Django 5.2.4 on 2025-07-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='recipients',
            new_name='recipient_emails',
        ),
    ]
