# Generated by Django 5.2.4 on 2025-07-15 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_leadership', models.CharField(blank=True, null=True)),
                ('teacher_character', models.CharField(blank=True, null=True)),
                ('teacher_scholarship', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, null=True)),
                ('screenshot_link', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('leadership_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_activities', to='profiles.leadershipprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_teacher', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, null=True)),
                ('screenshot_link', models.CharField(blank=True, null=True)),
                ('grades', models.JSONField(blank=True, default=list, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('service_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_activities', to='profiles.serviceprofile')),
            ],
        ),
    ]
