# Generated by Django 5.2.4 on 2025-07-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('screenshot_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('osis_last_four_digits', models.CharField(max_length=100, unique=True)),
                ('official_class', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.profile')),
                ('teacher_leadership', models.CharField()),
                ('teacher_character', models.CharField()),
                ('teacher_scholarship', models.CharField()),
            ],
            bases=('profiles.profile',),
        ),
        migrations.CreateModel(
            name='ServiceProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.profile')),
            ],
            bases=('profiles.profile',),
        ),
        migrations.CreateModel(
            name='LeadershipActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.activity')),
                ('description', models.TextField()),
                ('Leadership_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.leadershipprofile')),
            ],
            bases=('profiles.activity',),
        ),
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.activity')),
                ('grades', models.JSONField(default=list)),
                ('hours', models.IntegerField()),
                ('service_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.serviceprofile')),
            ],
            bases=('profiles.activity',),
        ),
    ]
