# Generated by Django 5.2.4 on 2025-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipprofile',
            name='character_recommendation_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadershipprofile',
            name='leadership_recommendation_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadershipprofile',
            name='scholarship_recommendation_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='recommendation_given',
            field=models.BooleanField(default=False),
        ),
    ]
