# Generated by Django 5.2.4 on 2025-07-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='osis_last_four_digits',
        ),
    ]
