# Generated by Django 5.2.4 on 2025-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
